#ifndef ADMIN_PAGE_H
#define ADMIN_PAGE_H

static const char ADMIN_HTML[] =
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>ESP32 设备管理</title>"
"<meta http-equiv='Cache-Control' content='no-cache, no-store, must-revalidate'>"
"<style>"
"* { margin: 0; padding: 0; box-sizing: border-box; }"
"body { font-family: Arial, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; padding: 20px; }"
".container { max-width: 500px; margin: 0 auto; background: white; border-radius: 10px; padding: 30px; box-shadow: 0 10px 30px rgba(0,0,0,0.2); }"
".header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 25px; }"
"h1 { color: #333; font-size: 22px; }"
".logout-btn { padding: 6px 12px; background: #dc3545; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 14px; }"
".section { margin-bottom: 25px; padding: 15px; background: #f8f9fa; border-radius: 8px; }"
".section h2 { color: #333; font-size: 16px; margin-bottom: 12px; border-left: 4px solid #667eea; padding-left: 8px; }"
".info-row { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #eee; font-size: 14px; }"
".info-row:last-child { border-bottom: none; }"
".info-label { color: #666; }"
".info-value { color: #333; font-weight: bold; }"
".form-group { margin-bottom: 15px; }"
"label { display: block; margin-bottom: 5px; color: #555; font-weight: bold; font-size: 14px; }"
"input, select { width: 100%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 14px; }"
"input:focus, select:focus { border-color: #667eea; outline: none; }"
".buttons { display: flex; gap: 10px; margin-top: 15px; }"
"button { padding: 10px 20px; background: #667eea; color: white; border: none; border-radius: 5px; font-size: 14px; cursor: pointer; }"
"button:hover { background: #764ba2; }"
"button.secondary { background: #6c757d; }"
"button.secondary:hover { background: #5a6268; }"
"button.danger { background: #dc3545; }"
"button.danger:hover { background: #c82333; }"
"button.scan-btn { background: #28a745; flex: 0 0 15%; padding: 10px 0; }"
"button.scan-btn:disabled { background: #ccc; cursor: not-allowed; }"
".status { margin-top: 10px; padding: 10px; border-radius: 5px; text-align: center; display: none; font-size: 14px; }"
".success { background: #d4edda; color: #155724; }"
".error { background: #f8d7da; color: #721c24; }"
".warning { background: #fff3cd; color: #856404; }"
".ota-box { margin-top: 10px; }"
"input[type='file'] { display: none; }"
".file-label { display: inline-block; padding: 8px 16px; background: #17a2b8; color: white; border-radius: 5px; cursor: pointer; font-size: 14px; }"
".file-label:hover { background: #138496; }"
".progress-bar { background: #eee; border-radius: 5px; overflow: hidden; height: 18px; margin-top: 10px; display: none; }"
".progress-fill { background: linear-gradient(90deg,#28a745,#20c997); height: 100%; width: 0%; transition: width 0.3s; border-radius: 5px; }"
".progress-text { margin-top: 6px; text-align: center; color: #666; font-size: 13px; }"
".nav { text-align: center; margin-top: 20px; }"
".nav a { color: #667eea; text-decoration: none; font-size: 14px; }"
".nav a:hover { text-decoration: underline; }"
".advanced { margin-top: 15px; padding-top: 15px; border-top: 1px dashed #ccc; }"
".advanced-toggle { color: #667eea; cursor: pointer; font-size: 14px; text-align: center; padding: 8px; }"
".advanced-content { display: none; margin-top: 10px; }"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<div class='header'>"
"<h1>设备管理</h1>"
"<button class='logout-btn' onclick='logout()'>退出</button>"
"</div>"
"<div class='section'>"
"<h2>设备信息</h2>"
"<div class='info-row'><span class='info-label'>WiFi 网络</span><span class='info-value' id='devWifi'>--</span></div>"
"<div class='info-row'><span class='info-label'>IP 地址</span><span class='info-value' id='devIp'>--</span></div>"
"<div class='info-row'><span class='info-label'>信号强度</span><span class='info-value' id='devRssi'>--</span></div>"
"<div class='info-row'><span class='info-label'>运行时间</span><span class='info-value' id='devUptime'>--</span></div>"
"<div class='info-row'><span class='info-label'>空闲内存</span><span class='info-value' id='devHeap'>--</span></div>"
"<div class='info-row'><span class='info-label'>运行分区</span><span class='info-value' id='devPartition'>--</span></div>"
"</div>"
"<div class='section'>"
"<h2>修改管理密码</h2>"
"<form id='pwdForm'>"
"<div class='form-group'>"
"<label>新用户名</label>"
"<input type='text' id='newUser' placeholder='admin' required>"
"</div>"
"<div class='form-group'>"
"<label>新密码</label>"
"<input type='password' id='newPass' placeholder='新密码' required>"
"</div>"
"<div class='form-group'>"
"<label>确认密码</label>"
"<input type='password' id='confirmPass' placeholder='确认密码' required>"
"</div>"
"<button type='submit'>保存密码</button>"
"<div id='pwdStatus' class='status'></div>"
"</form>"
"</div>"
"<div class='section'>"
"<h2>固件升级 (OTA)</h2>"
"<div class='warning' style='padding:10px;border-radius:4px;margin-bottom:12px;font-size:13px;'>升级过程中请勿断电！</div>"
"<input type='file' id='otaFile' accept='.bin' onchange='fileSelected()'>"
"<label for='otaFile' class='file-label'>选择固件</label>"
"<span id='fileName' style='margin-left:10px;color:#666;font-size:13px;'></span>"
"<div style='margin-top:10px;'>"
"<button id='uploadBtn' onclick='startUpload()' disabled style='background:#28a745;'>开始升级</button>"
"</div>"
"<div class='progress-bar' id='progressBar'><div class='progress-fill' id='progressFill'></div></div>"
"<div class='progress-text' id='progressText'></div>"
"</div>"
"<div class='advanced'>"
"<div class='advanced-toggle' onclick='toggleNetConfig()'>&#9654; 网络配置 (WiFi / MQTT)</div>"
"<div class='advanced-content' id='netConfigContent'>"
"<div class='warning' style='padding:10px;border-radius:4px;margin-bottom:12px;font-size:13px;'>"
"警告：修改网络配置可能导致设备断开当前连接。"
"</div>"
"<form id='netForm'>"
"<div class='form-group'>"
"<label>WiFi 网络:</label>"
"<div style='display:flex;gap:8px;'>"
"<select id='wifi_ssid' style='flex:1;'>"
"<option value=''>-- 请先扫描 --</option>"
"</select>"
"<button type='button' id='scanBtn' onclick='scanWiFi()' class='scan-btn'>扫描</button>"
"</div>"
"</div>"
"<div class='form-group'>"
"<label>WiFi 密码:</label>"
"<div style='display:flex;gap:8px;'>"
"<input type='password' id='wifi_password' style='flex:1;'>"
"<button type='button' onclick='togglePwd(\"wifi_password\",this)' style='flex:0 0 15%;padding:10px 0;background:#6c757d;color:white;border:none;border-radius:5px;font-size:14px;cursor:pointer;'>显示</button>"
"</div>"
"</div>"
"<div class='form-group'>"
"<label>MQTT Broker:</label>"
"<input type='text' id='mqtt_uri' placeholder='broker.example.com'>"
"</div>"
"<div class='form-group'>"
"<label>MQTT 端口:</label>"
"<input type='number' id='mqtt_port' value='1883' min='1' max='65535'>"
"</div>"
"<div class='form-group'>"
"<label>MQTT 用户名:</label>"
"<input type='text' id='mqtt_username'>"
"</div>"
"<div class='form-group'>"
"<label>MQTT 密码:</label>"
"<div style='display:flex;gap:8px;'>"
"<input type='password' id='mqtt_password' style='flex:1;'>"
"<button type='button' onclick='togglePwd(\"mqtt_password\",this)' style='flex:0 0 15%;padding:10px 0;background:#6c757d;color:white;border:none;border-radius:5px;font-size:14px;cursor:pointer;'>显示</button>"
"</div>"
"</div>"
"<div class='buttons'>"
"<button type='submit'>保存网络配置</button>"
"<button type='button' class='secondary' onclick='resetNetConfig()'>重置</button>"
"</div>"
"</form>"
"<div id='netStatus' class='status' style='margin-top:10px;'></div>"
"</div>"
"</div>"
"</div>"
"<script>"
"const token=localStorage.getItem('auth_token');"
"if(!token){window.location.href='/login.html';}"
"function togglePwd(id,btn){const el=document.getElementById(id);if(el.type==='password'){el.type='text';btn.textContent='隐藏';}else{el.type='password';btn.textContent='显示';}}"
"function toggleNetConfig(){const el=document.getElementById('netConfigContent');const arrow=document.querySelector('.advanced-toggle');el.style.display=el.style.display==='block'?'none':'block';arrow.innerHTML=el.style.display==='block'?'&#9660; 网络配置 (WiFi / MQTT)':'&#9654; 网络配置 (WiFi / MQTT)';}"
"async function loadInfo(){"
"try{"
"const res=await fetch('/api/status',{headers:{'Authorization':'Bearer '+token}});"
"if(!res.ok){if(res.status===401){window.location.href='/login.html';return;}throw new Error('failed');}"
"const data=await res.json();"
"document.getElementById('devWifi').textContent=data.wifi_ssid||'--';"
"document.getElementById('devIp').textContent=data.ip||'--';"
"document.getElementById('devRssi').textContent=(data.rssi?data.rssi+' dBm':'--');"
"document.getElementById('devUptime').textContent=data.uptime||'--';"
"document.getElementById('devHeap').textContent=data.heap_free?data.heap_free+' B':'--';"
"document.getElementById('devPartition').textContent=data.partition||'--';"
"}catch(e){console.log('loadInfo error',e);}"
"}"
"async function loadNetConfig(){"
"try{"
"const res=await fetch('/api/config',{headers:{'Authorization':'Bearer '+token}});"
"if(!res.ok)return;"
"const data=await res.json();"
"const select=document.getElementById('wifi_ssid');"
"const saved=data.wifi_ssid||'';"
"if(saved&&!select.querySelector('option[value=\"'+saved+'\"]')){const opt=document.createElement('option');opt.value=saved;opt.textContent=saved;select.appendChild(opt);}"
"select.value=saved;"
"document.getElementById('mqtt_uri').value=data.mqtt_uri||'';"
"document.getElementById('mqtt_port').value=data.mqtt_port||1883;"
"document.getElementById('mqtt_username').value=data.mqtt_username||'';"
"}catch(e){console.log('loadNetConfig error',e);}"
"}"
"async function scanWiFi(){"
"const btn=document.getElementById('scanBtn');const select=document.getElementById('wifi_ssid');"
"btn.disabled=true;btn.textContent='...';"
"try{"
"const res=await fetch('/api/scan',{headers:{'Authorization':'Bearer '+token}});"
"if(!res.ok)throw new Error('scan failed');"
"const data=await res.json();"
"select.innerHTML='<option value=\"\">-- 请选择 WiFi --</option>';"
"data.sort((a,b)=>b.rssi-a.rssi);"
"data.forEach(ap=>{const opt=document.createElement('option');opt.value=ap.ssid;opt.textContent=(ap.security==='OPEN'?'':'🔒 ')+ap.ssid+' ('+ap.rssi+'dBm)';select.appendChild(opt);});"
"if(data.length===0)select.innerHTML='<option value=\"\">未找到网络</option>';"
"}catch(e){showNetStatus('扫描失败','error');}"
"btn.disabled=false;btn.textContent='扫描';"
"}"
"document.getElementById('pwdForm').addEventListener('submit',async(e)=>{"
"e.preventDefault();"
"const user=document.getElementById('newUser').value;"
"const pass=document.getElementById('newPass').value;"
"const confirm=document.getElementById('confirmPass').value;"
"const status=document.getElementById('pwdStatus');"
"if(pass!==confirm){showStatus(status,'密码不一致','error');return;}"
"if(pass.length<6){showStatus(status,'密码至少6位','error');return;}"
"try{"
"const res=await fetch('/api/admin_credentials',{"
"method:'POST',"
"headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},"
"body:JSON.stringify({username:user,password:pass})"
"});"
"const data=await res.json();"
"if(res.ok){showStatus(status,'密码修改成功，请重新登录','success');setTimeout(()=>{logout();},2000);}"
"else{showStatus(status,data.error||'修改失败','error');}"
"}catch(err){showStatus(status,'网络错误','error');}"
"});"
"document.getElementById('netForm').addEventListener('submit',async(e)=>{"
"e.preventDefault();"
"const config={"
"wifi_ssid:document.getElementById('wifi_ssid').value,"
"wifi_password:document.getElementById('wifi_password').value,"
"mqtt_uri:document.getElementById('mqtt_uri').value,"
"mqtt_port:parseInt(document.getElementById('mqtt_port').value),"
"mqtt_username:document.getElementById('mqtt_username').value,"
"mqtt_password:document.getElementById('mqtt_password').value"
"};"
"if(!config.wifi_ssid||!config.mqtt_uri){showNetStatus('WiFi和MQTT Broker不能为空','error');return;}"
"const btn=e.target.querySelector('button[type=\"submit\"]');btn.disabled=true;btn.textContent='保存中...';"
"try{"
"const res=await fetch('/api/config',{"
"method:'POST',"
"headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},"
"body:JSON.stringify(config)"
"});"
"if(res.ok){showNetStatus('网络配置保存成功！设备将重新连接...','success');}"
"else{showNetStatus('保存失败','error');}"
"}catch(e){showNetStatus('网络错误','error');}"
"btn.disabled=false;btn.textContent='保存网络配置';"
"});"
"function showStatus(el,msg,type){el.textContent=msg;el.className='status '+type;el.style.display='block';}"
"function showNetStatus(msg,type){const el=document.getElementById('netStatus');el.textContent=msg;el.className='status '+type;el.style.display='block';}"
"function resetNetConfig(){"
"document.getElementById('wifi_ssid').innerHTML='<option value=\"\">-- 请先扫描 --</option>';"
"document.getElementById('wifi_password').value='';"
"document.getElementById('mqtt_uri').value='';"
"document.getElementById('mqtt_port').value='1883';"
"document.getElementById('mqtt_username').value='';"
"document.getElementById('mqtt_password').value='';"
"document.getElementById('netStatus').style.display='none';"
"}"
"function fileSelected(){"
"const file=document.getElementById('otaFile').files[0];"
"if(file){document.getElementById('fileName').textContent=file.name+' ('+(file.size/1024).toFixed(1)+' KB)';document.getElementById('uploadBtn').disabled=false;}"
"}"
"function startUpload(){"
"const file=document.getElementById('otaFile').files[0];"
"if(!file){alert('请先选择固件');return;}"
"if(!confirm('确定要升级固件吗？升级过程中请勿断电！'))return;"
"const bar=document.getElementById('progressBar');const fill=document.getElementById('progressFill');const text=document.getElementById('progressText');const btn=document.getElementById('uploadBtn');"
"bar.style.display='block';fill.style.width='0%';text.textContent='上传中...';text.style.color='#666';btn.disabled=true;"
"const xhr=new XMLHttpRequest();"
"xhr.open('POST','/api/ota',true);"
"xhr.setRequestHeader('Authorization','Bearer '+token);"
"xhr.upload.onprogress=function(e){if(e.lengthComputable){const pct=Math.round((e.loaded/e.total)*100);fill.style.width=pct+'%';text.textContent='上传中... '+pct+'%';}};"
"xhr.onload=function(){"
"if(xhr.status===200){fill.style.width='100%';text.textContent='升级成功！设备即将重启...';text.style.color='#28a745';}"
"else if(xhr.status===401){text.textContent='认证失败';text.style.color='#dc3545';btn.disabled=false;}"
"else{text.textContent='升级失败: '+xhr.status;text.style.color='#dc3545';btn.disabled=false;}"
"};"
"xhr.onerror=function(){text.textContent='上传失败';text.style.color='#dc3545';btn.disabled=false;};"
"xhr.send(file);"
"}"
"function logout(){localStorage.removeItem('auth_token');window.location.href='/login.html';}"
"loadInfo();"
"loadNetConfig();"
"setInterval(loadInfo,10000);"
"</script>"
"</body>"
"</html>";

#endif
