#ifndef LOGIN_PAGE_H
#define LOGIN_PAGE_H

static const char LOGIN_HTML[] =
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>ESP32 登录</title>"
"<meta http-equiv='Cache-Control' content='no-cache, no-store, must-revalidate'>"
"<style>"
"* { margin: 0; padding: 0; box-sizing: border-box; }"
"body { font-family: Arial, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; }"
".login-box { max-width: 400px; width: 100%; background: white; border-radius: 10px; padding: 40px; box-shadow: 0 10px 30px rgba(0,0,0,0.2); }"
"h1 { text-align: center; color: #333; margin-bottom: 30px; }"
".form-group { margin-bottom: 20px; }"
"label { display: block; margin-bottom: 5px; color: #555; font-weight: bold; }"
"input { width: 100%; padding: 12px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px; }"
"input:focus { border-color: #667eea; outline: none; }"
"button { width: 100%; padding: 12px; background: #667eea; color: white; border: none; border-radius: 5px; font-size: 16px; cursor: pointer; margin-top: 10px; }"
"button:hover { background: #764ba2; }"
".error { color: #dc3545; text-align: center; margin-top: 15px; display: none; }"
".hint { color: #666; font-size: 13px; text-align: center; margin-top: 20px; }"
"</style>"
"</head>"
"<body>"
"<div class='login-box'>"
"<h1>ESP32 管理登录</h1>"
"<form id='loginForm'>"
"<div class='form-group'>"
"<label>用户名</label>"
"<input type='text' id='username' required placeholder='admin'>"
"</div>"
"<div class='form-group'>"
"<label>密码</label>"
"<input type='password' id='password' required placeholder='密码'>"
"</div>"
"<button type='submit'>登录</button>"
"<div id='error' class='error'></div>"
"</form>"
"<div class='hint'>首次登录默认账号: admin / synaflow2024</div>"
"</div>"
"<script>"
"document.getElementById('loginForm').addEventListener('submit', async (e) => {"
"e.preventDefault();"
"const user = document.getElementById('username').value;"
"const pass = document.getElementById('password').value;"
"const errEl = document.getElementById('error');"
"errEl.style.display = 'none';"
"try {"
"const res = await fetch('/api/login', {"
"method: 'POST',"
"headers: {'Content-Type': 'application/json'},"
"body: JSON.stringify({username: user, password: pass})"
"});"
"const data = await res.json();"
"if (res.ok && data.token) {"
"localStorage.setItem('auth_token', data.token);"
"window.location.href = '/index.html';"
"} else {"
"errEl.textContent = data.error || '登录失败';"
"errEl.style.display = 'block';"
"}"
"} catch(e) {"
"errEl.textContent = '网络错误';"
"errEl.style.display = 'block';"
"}"
"});"
"</script>"
"</body>"
"</html>";

#endif
