#ifndef OTA_PAGE_H
#define OTA_PAGE_H

static const char OTA_HTML[] =
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>ESP32 固件升级</title>"
"<meta http-equiv='Cache-Control' content='no-cache, no-store, must-revalidate'>"
"<style>"
"* { margin: 0; padding: 0; box-sizing: border-box; }"
"body { font-family: Arial, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; padding: 20px; }"
".container { max-width: 500px; margin: 0 auto; background: white; border-radius: 10px; padding: 30px; box-shadow: 0 10px 30px rgba(0,0,0,0.2); }"
".header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; }"
"h1 { color: #333; }"
".logout-btn { padding: 6px 12px; background: #dc3545; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 14px; }"
".info { background: #e7f3ff; border-left: 4px solid #2196F3; padding: 12px; margin-bottom: 20px; border-radius: 4px; color: #333; font-size: 14px; }"
".form-group { margin-bottom: 20px; }"
"label { display: block; margin-bottom: 5px; color: #555; font-weight: bold; }"
"input[type='file'] { display: none; }"
".file-label { display: inline-block; padding: 10px 20px; background: #17a2b8; color: white; border-radius: 5px; cursor: pointer; }"
".file-label:hover { background: #138496; }"
".buttons { display: flex; gap: 10px; margin-top: 20px; justify-content: center; }"
"button { padding: 12px 24px; background: #28a745; color: white; border: none; border-radius: 5px; font-size: 16px; cursor: pointer; }"
"button:disabled { background: #999; cursor: not-allowed; }"
"button.danger { background: #dc3545; }"
"button.danger:hover { background: #c82333; }"
".progress-box { margin-top: 20px; display: none; }"
".progress-bar { background: #eee; border-radius: 5px; overflow: hidden; height: 20px; }"
".progress-fill { background: linear-gradient(90deg,#28a745,#20c997); height: 100%; width: 0%; transition: width 0.3s; border-radius: 5px; }"
".status { margin-top: 10px; text-align: center; color: #666; font-size: 14px; }"
".nav { text-align: center; margin-top: 20px; }"
".nav a { color: #667eea; text-decoration: none; }"
".nav a:hover { text-decoration: underline; }"
".warning { background: #fff3cd; border-left: 4px solid #ffc107; padding: 12px; margin-bottom: 20px; border-radius: 4px; color: #856404; font-size: 14px; }"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<div class='header'>"
"<h1>固件升级 (OTA)</h1>"
"<button class='logout-btn' onclick='logout()'>退出</button>"
"</div>"
"<div class='warning'>"
"<strong>警告：</strong>升级过程中请勿断电！错误的固件可能导致设备无法启动。"
"</div>"
"<div class='info' id='otaInfo'>正在获取当前版本信息...</div>"
"<div class='form-group'>"
"<label>选择固件文件 (.bin):</label>"
"<input type='file' id='otaFile' accept='.bin' onchange='fileSelected()'>"
"<label for='otaFile' class='file-label'>选择固件</label>"
"<div id='fileName' style='margin-top:10px;color:#666;font-size:14px;'></div>"
"</div>"
"<div class='buttons'>"
"<button id='uploadBtn' onclick='startUpload()' disabled>开始升级</button>"
"</div>"
"<div class='progress-box' id='progressBox'>"
"<div class='progress-bar'><div class='progress-fill' id='progressFill'></div></div>"
"<div class='status' id='statusText'>准备中...</div>"
"</div>"
"<div class='nav'>"
"<a href='/index.html'>&larr; 返回 WiFi 配置</a>"
"</div>"
"</div>"
"<script>"
"const token=localStorage.getItem('auth_token');"
"if(!token){window.location.href='/login.html';}"
"async function loadOtaInfo(){"
"try{"
"const res=await fetch('/api/ota',{headers:{'Authorization':'Bearer '+token}});"
"if(!res.ok){if(res.status===401){window.location.href='/login.html';return;}throw new Error('failed');}"
"const data=await res.json();"
"document.getElementById('otaInfo').innerHTML='运行分区: <b>'+(data.running_partition||'unknown')+'</b><br>启动分区: <b>'+(data.boot_partition||'unknown')+'</b>';"
"}catch(e){document.getElementById('otaInfo').textContent='无法获取版本信息';}"
"}"
"function fileSelected(){"
"const file=document.getElementById('otaFile').files[0];"
"if(file){"
"document.getElementById('fileName').textContent=file.name+' ('+(file.size/1024).toFixed(1)+' KB)';"
"document.getElementById('uploadBtn').disabled=false;"
"}"
"}"
"function startUpload(){"
"const file=document.getElementById('otaFile').files[0];"
"if(!file){alert('请先选择固件文件');return;}"
"if(!confirm('确定要升级固件吗？升级过程中请勿断电！\\n\\n文件: '+file.name+' ('+(file.size/1024).toFixed(1)+' KB)'))return;"
"const progressBox=document.getElementById('progressBox');"
"const fill=document.getElementById('progressFill');"
"const status=document.getElementById('statusText');"
"const btn=document.getElementById('uploadBtn');"
"progressBox.style.display='block';"
"fill.style.width='0%';"
"status.textContent='上传中...';"
"status.style.color='#666';"
"btn.disabled=true;"
"const xhr=new XMLHttpRequest();"
"xhr.open('POST','/api/ota',true);"
"xhr.setRequestHeader('Authorization','Bearer '+token);"
"xhr.upload.onprogress=function(e){"
"if(e.lengthComputable){"
"const pct=Math.round((e.loaded/e.total)*100);"
"fill.style.width=pct+'%';"
"status.textContent='上传中... '+pct+'%';"
"}"
"};"
"xhr.onload=function(){"
"if(xhr.status===200){"
"fill.style.width='100%';"
"status.textContent='升级成功！设备即将重启...';"
"status.style.color='#28a745';"
"}else if(xhr.status===401){"
"status.textContent='认证失败，请重新登录';"
"status.style.color='#dc3545';"
"setTimeout(()=>window.location.href='/login.html',2000);"
"}else{"
"status.textContent='升级失败: '+xhr.status;"
"status.style.color='#dc3545';"
"btn.disabled=false;"
"}"
"};"
"xhr.onerror=function(){"
"status.textContent='上传失败，请重试';"
"status.style.color='#dc3545';"
"btn.disabled=false;"
"};"
"xhr.send(file);"
"}"
"function logout(){localStorage.removeItem('auth_token');window.location.href='/login.html';}"
"loadOtaInfo();"
"</script>"
"</body>"
"</html>";

#endif
