#ifndef WEB_PAGE_H
#define WEB_PAGE_H

static const char INDEX_HTML[] =
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>ESP32 配置</title>"
"<style>"
"* { margin: 0; padding: 0; box-sizing: border-box; }"
"body { font-family: Arial, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; padding: 20px; }"
".container { max-width: 500px; margin: 0 auto; background: white; border-radius: 10px; padding: 30px; box-shadow: 0 10px 30px rgba(0,0,0,0.2); }"
"h1 { text-align: center; color: #333; margin-bottom: 30px; }"
".form-group { margin-bottom: 20px; }"
"label { display: block; margin-bottom: 5px; color: #555; font-weight: bold; }"
"input { width: 100%; padding: 12px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px; }"
"input:focus { border-color: #667eea; outline: none; }"
".buttons { display: flex; gap: 10px; margin-top: 20px; }"
"button { flex: 1; padding: 12px; background: #667eea; color: white; border: none; border-radius: 5px; font-size: 16px; cursor: pointer; }"
"button:hover { background: #764ba2; }"
"button.secondary { background: #6c757d; }"
"button.secondary:hover { background: #5a6268; }"
".status { margin-top: 20px; padding: 15px; border-radius: 5px; text-align: center; }"
".success { background: #d4edda; color: #155724; }"
".error { background: #f8d7da; color: #721c24; }"
".loading { opacity: 0.5; pointer-events: none; }"
".scan-btn { background: #28a745; }"
".scan-btn:disabled { background: #ccc; cursor: not-allowed; }"
".scan-loading { animation: pulse 1s infinite; }"
"@keyframes pulse { 0%,100% { opacity:1; } 50% { opacity:0.5; } }"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<h1>📱 ESP32 配置</h1>"
"<form id='configForm'>"
"<div class='form-group'>"
"<label>WiFi 网络:</label>"
"<div style='display:flex;gap:8px;'>"
"<select id='wifi_ssid' style='flex:1;padding:12px;border:2px solid #ddd;border-radius:5px;font-size:16px;background:white;' required>"
"<option value=''>-- 请先扫描 --</option>"
"</select>"
"<button type='button' id='scanBtn' onclick='scanWiFi()' style='padding:12px 16px;background:#28a745;color:white;border:none;border-radius:5px;font-size:14px;cursor:pointer;white-space:nowrap;'>扫描</button>"
"</div>"
"</div>"
"<div class='form-group'>"
"<label>WiFi 密码:</label>"
"<input type='password' id='wifi_password'>"
"</div>"
"<div class='form-group'>"
"<label>MQTT Broker:</label>"
"<input type='text' id='mqtt_uri' placeholder='broker.example.com' required>"
"</div>"
"<div class='form-group'>"
"<label>MQTT 端口:</label>"
"<input type='number' id='mqtt_port' value='1883' min='1' max='65535' required>"
"</div>"
"<div class='form-group'>"
"<label>MQTT 用户名:</label>"
"<input type='text' id='mqtt_username'>"
"</div>"
"<div class='form-group'>"
"<label>MQTT 密码:</label>"
"<input type='password' id='mqtt_password'>"
"</div>"
"<div class='buttons'>"
"<button type='submit'>保存配置</button>"
"<button type='button' class='secondary' onclick='resetConfig()'>重置</button>"
"</div>"
"</form>"
"<div id='status' class='status' style='display:none;'></div>"
"</div>"
"<script>"
"async function loadConfig() {"
"try {"
"const res = await fetch('/api/config');"
"const data = await res.json();"
"const select = document.getElementById('wifi_ssid');"
"const savedSsid = data.wifi_ssid || '';"
"if (savedSsid && !select.querySelector('option[value=\"' + savedSsid + '\"]')) {"
"const opt = document.createElement('option');"
"opt.value = savedSsid;"
"opt.textContent = savedSsid;"
"select.appendChild(opt);"
"}"
"select.value = savedSsid;"
"document.getElementById('mqtt_uri').value = data.mqtt_uri || '';"
"document.getElementById('mqtt_port').value = data.mqtt_port || 1883;"
"document.getElementById('mqtt_username').value = data.mqtt_username || '';"
"} catch(e) {"
"console.log('Load config failed:', e);"
"}"
"}"
"async function scanWiFi() {"
"const btn = document.getElementById('scanBtn');"
"const select = document.getElementById('wifi_ssid');"
"btn.disabled = true;"
"btn.textContent = '扫描中...';"
"btn.classList.add('scan-loading');"
"try {"
"const res = await fetch('/api/scan');"
"if (!res.ok) throw new Error('Scan failed');"
"const data = await res.json();"
"select.innerHTML = '<option value=\"\">-- 请选择 WiFi --</option>';"
"data.sort((a,b) => b.rssi - a.rssi);"
"data.forEach(ap => {"
"const opt = document.createElement('option');"
"opt.value = ap.ssid;"
"const lock = ap.security === 'OPEN' ? '' : '🔒';"
"opt.textContent = lock + ' ' + ap.ssid + ' (' + ap.rssi + 'dBm)';"
"select.appendChild(opt);"
"});"
"if (data.length === 0) {"
"select.innerHTML = '<option value=\"\">未找到网络</option>';"
"}"
"} catch(e) {"
"showStatus('扫描失败，请重试', 'error');"
"}"
"btn.disabled = false;"
"btn.textContent = '扫描';"
"btn.classList.remove('scan-loading');"
"}"
"document.getElementById('configForm').addEventListener('submit', async (e) => {"
"e.preventDefault();"
"const config = {"
"wifi_ssid: document.getElementById('wifi_ssid').value,"
"wifi_password: document.getElementById('wifi_password').value,"
"mqtt_uri: document.getElementById('mqtt_uri').value,"
"mqtt_port: parseInt(document.getElementById('mqtt_port').value),"
"mqtt_username: document.getElementById('mqtt_username').value,"
"mqtt_password: document.getElementById('mqtt_password').value"
"};"
"const btn = e.target.querySelector('button[type=\"submit\"]');"
"btn.disabled = true;"
"btn.textContent = '保存中...';"
"try {"
"const res = await fetch('/api/config', {"
"method: 'POST',"
"headers: {'Content-Type': 'application/json'},"
"body: JSON.stringify(config)"
"});"
"if (res.ok) {"
"showStatus('配置保存成功！设备正在连接...', 'success');"
"} else {"
"showStatus('保存失败，请重试', 'error');"
"}"
"} catch(e) {"
"showStatus('网络错误，请重试', 'error');"
"}"
"btn.disabled = false;"
"btn.textContent = '保存配置';"
"});"
"function resetConfig() {"
"document.getElementById('wifi_ssid').innerHTML = '<option value=\"\">-- 请先扫描 --</option>';"
"document.getElementById('wifi_password').value = '';"
"document.getElementById('mqtt_uri').value = '';"
"document.getElementById('mqtt_port').value = '1883';"
"document.getElementById('mqtt_username').value = '';"
"document.getElementById('mqtt_password').value = '';"
"hideStatus();"
"}"
"function showStatus(msg, type) {"
"const el = document.getElementById('status');"
"el.textContent = msg;"
"el.className = 'status ' + type;"
"el.style.display = 'block';"
"}"
"function hideStatus() {"
"document.getElementById('status').style.display = 'none';"
"}"
"loadConfig();"
"// Auto scan WiFi when page loads"
"window.addEventListener('load', () => {"
"    setTimeout(scanWiFi, 500);"
"});"
"</script>"
"</body>"
"</html>";

#endif
