#ifndef WEB_PAGE_H
#define WEB_PAGE_H

static const char INDEX_HTML[] =
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>ESP32 配置</title>"
"<meta http-equiv='Cache-Control' content='no-cache, no-store, must-revalidate'>"
"<meta http-equiv='Pragma' content='no-cache'>"
"<meta http-equiv='Expires' content='0'>"
"<style>"
"* { margin: 0; padding: 0; box-sizing: border-box; }"
"body { font-family: Arial, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; padding: 20px; }"
".container { max-width: 500px; margin: 0 auto; background: white; border-radius: 10px; padding: 30px; box-shadow: 0 10px 30px rgba(0,0,0,0.2); }"
"h1 { text-align: center; color: #333; margin-bottom: 30px; }"
".form-group { margin-bottom: 20px; }"
"label { display: block; margin-bottom: 5px; color: #555; font-weight: bold; }"
"input { width: 100%; padding: 12px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px; }"
"input:focus { border-color: #667eea; outline: none; }"
".buttons { display: flex; gap: 10px; margin-top: 20px; }"
"button { flex: 1; padding: 12px; background: #667eea; color: white; border: none; border-radius: 5px; font-size: 16px; cursor: pointer; }"
"button:hover { background: #764ba2; }"
"button.secondary { background: #6c757d; }"
"button.secondary:hover { background: #5a6268; }"
".status { margin-top: 20px; padding: 15px; border-radius: 5px; text-align: center; }"
".success { background: #d4edda; color: #155724; }"
".error { background: #f8d7da; color: #721c24; }"
".loading { opacity: 0.5; pointer-events: none; }"
".scan-btn { background: #28a745; }"
".scan-btn:disabled { background: #ccc; cursor: not-allowed; }"
".scan-loading { animation: pulse 1s infinite; }"
"@keyframes pulse { 0%,100% { opacity:1; } 50% { opacity:0.5; } }"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<h1>📱 ESP32 配置 v2</h1>"
"<form id='configForm'>"
"<div class='form-group'>"
"<label>WiFi 网络:</label>"
"<div style='display:flex;gap:8px;'>"
"<select id='wifi_ssid' style='flex:1;min-width:0;max-width:calc(100% - 70px);padding:12px;border:2px solid #ddd;border-radius:5px;font-size:16px;background:white;text-overflow:ellipsis;overflow:hidden;white-space:nowrap;' required>"
"<option value=''>-- 请先扫描 --</option>"
"</select>"
"<button type='button' id='scanBtn' onclick='scanWiFi()' style='width:15%;padding:12px 0;background:#28a745;color:white;border:none;border-radius:5px;font-size:14px;cursor:pointer;white-space:nowrap;'>扫描</button>"
"</div>"
"</div>"
"<div class='form-group'>"
"<label>WiFi 密码:</label>"
"<div style='display:flex;gap:8px;'>"
"<input type='password' id='wifi_password' style='flex:1;'>"
"<button type='button' onclick='togglePassword(\"wifi_password\", \"wifiToggleBtn\")' id='wifiToggleBtn' style='width:15%;padding:12px 0;background:#6c757d;color:white;border:none;border-radius:5px;font-size:14px;cursor:pointer;white-space:nowrap;'>显示</button>"
"</div>"
"</div>"
"<div class='form-group'>"
"<label>MQTT Broker:</label>"
"<input type='text' id='mqtt_uri' placeholder='broker.example.com' required>"
"</div>"
"<div class='form-group'>"
"<label>MQTT 端口:</label>"
"<input type='number' id='mqtt_port' value='1883' min='1' max='65535' required>"
"</div>"
"<div class='form-group'>"
"<label>MQTT 用户名:</label>"
"<input type='text' id='mqtt_username'>"
"</div>"
"<div class='form-group'>"
"<label>MQTT 密码:</label>"
"<div style='display:flex;gap:8px;'>"
"<input type='password' id='mqtt_password' style='flex:1;'>"
"<button type='button' onclick='togglePassword(\"mqtt_password\", \"mqttToggleBtn\")' id='mqttToggleBtn' style='width:15%;padding:12px 0;background:#6c757d;color:white;border:none;border-radius:5px;font-size:14px;cursor:pointer;white-space:nowrap;'>显示</button>"
"</div>"
"</div>"
"<div class='buttons'>"
"<button type='submit'>保存配置</button>"
"<button type='button' class='secondary' onclick='resetConfig()'>重置</button>"
"</div>"
"</form>"
"<div id='status' class='status' style='display:none;'></div>"
"<hr style='margin:30px 0;border:none;border-top:1px solid #eee;'>"
"<div style='text-align:center;'>"
"<h3 style='color:#333;margin-bottom:15px;'>固件升级 (OTA)</h3>"
"<div style='margin-bottom:15px;'>"
"<input type='text' id='otaUser' placeholder='用户名' style='padding:8px 12px;margin:0 5px;border:1px solid #ddd;border-radius:4px;width:120px;font-size:14px;'>"
"<input type='password' id='otaPass' placeholder='密码' style='padding:8px 12px;margin:0 5px;border:1px solid #ddd;border-radius:4px;width:120px;font-size:14px;'>"
"</div>"
"<input type='file' id='otaFile' accept='.bin' style='display:none;' onchange='otaFileSelected(this)'>"
"<div class='buttons' style='justify-content:center;'>"
"<button type='button' onclick='document.getElementById(\"otaFile\").value=\"\";document.getElementById(\"otaFile\").click()' style='padding:12px 24px;background:#17a2b8;color:white;border:none;border-radius:5px;font-size:14px;cursor:pointer;'>选择固件</button>"
"<button type='button' id='otaUploadBtn' onclick='otaUpload()' disabled style='padding:12px 24px;background:#999;color:white;border:none;border-radius:5px;font-size:14px;cursor:not-allowed;'>开始升级</button>"
"</div>"
"<div id='otaFileName' style='margin-top:10px;color:#666;font-size:14px;'></div>"
"<div id='otaCrc' style='margin-top:5px;color:#666;font-size:13px;display:none;'></div>"
"<div id='otaProgress' style='display:none;margin-top:15px;'>"
"<div style='background:#eee;border-radius:5px;overflow:hidden;height:20px;'>"
"<div id='otaProgressBar' style='background:linear-gradient(90deg,#17a2b8,#20c997);height:100%;width:0%;transition:width 0.3s;border-radius:5px;'></div>"
"</div>"
"<div id='otaStatus' style='margin-top:8px;color:#666;font-size:13px;'>准备中...</div>"
"</div>"
"</div>"
"</div>"
"<script>"
"function togglePassword(inputId, btnId) {"
"    const pwdInput = document.getElementById(inputId);"
"    const toggleBtn = document.getElementById(btnId);"
"    if (pwdInput.type === 'password') {"
"        pwdInput.type = 'text';"
"        toggleBtn.textContent = '隐藏';"
"    } else {"
"        pwdInput.type = 'password';"
"        toggleBtn.textContent = '显示';"
"    }"
"}"
"async function loadConfig() {"
"try {"
"const res = await fetch('/api/config');"
"const data = await res.json();"
"const select = document.getElementById('wifi_ssid');"
"const savedSsid = data.wifi_ssid || '';"
"if (savedSsid && !select.querySelector('option[value=\"' + savedSsid + '\"]')) {"
"const opt = document.createElement('option');"
"opt.value = savedSsid;"
"opt.textContent = savedSsid;"
"select.appendChild(opt);"
"}"
"select.value = savedSsid;"
"document.getElementById('mqtt_uri').value = data.mqtt_uri || '';"
"document.getElementById('mqtt_port').value = data.mqtt_port || 1883;"
"document.getElementById('mqtt_username').value = data.mqtt_username || '';"
"} catch(e) {"
"console.log('Load config failed:', e);"
"}"
"}"
"async function scanWiFi() {"
"const btn = document.getElementById('scanBtn');"
"const select = document.getElementById('wifi_ssid');"
"btn.disabled = true;"
"btn.textContent = '扫描中...';"
"btn.classList.add('scan-loading');"
"try {"
"const res = await fetch('/api/scan');"
"if (!res.ok) throw new Error('Scan failed');"
"const data = await res.json();"
"select.innerHTML = '<option value=\"\">-- 请选择 WiFi --</option>';"
"data.sort((a,b) => b.rssi - a.rssi);"
"data.forEach(ap => {"
"const opt = document.createElement('option');"
"opt.value = ap.ssid;"
"const lock = ap.security === 'OPEN' ? '' : '🔒';"
"opt.textContent = lock + ' ' + ap.ssid + ' (' + ap.rssi + 'dBm)';"
"select.appendChild(opt);"
"});"
"if (data.length === 0) {"
"select.innerHTML = '<option value=\"\">未找到网络</option>';"
"}"
"} catch(e) {"
"showStatus('扫描失败，请重试', 'error');"
"}"
"btn.disabled = false;"
"btn.textContent = '扫描';"
"btn.classList.remove('scan-loading');"
"}"
"document.getElementById('configForm').addEventListener('submit', async (e) => {"
"e.preventDefault();"
"const config = {"
"wifi_ssid: document.getElementById('wifi_ssid').value,"
"wifi_password: document.getElementById('wifi_password').value,"
"mqtt_uri: document.getElementById('mqtt_uri').value,"
"mqtt_port: parseInt(document.getElementById('mqtt_port').value),"
"mqtt_username: document.getElementById('mqtt_username').value,"
"mqtt_password: document.getElementById('mqtt_password').value"
"};"
"const btn = e.target.querySelector('button[type=\"submit\"]');"
"btn.disabled = true;"
"btn.textContent = '保存中...';"
"try {"
"const res = await fetch('/api/config', {"
"method: 'POST',"
"headers: {'Content-Type': 'application/json'},"
"body: JSON.stringify(config)"
"});"
"if (res.ok) {"
"showStatus('配置保存成功！设备正在连接...', 'success');"
"} else {"
"showStatus('保存失败，请重试', 'error');"
"}"
"} catch(e) {"
"showStatus('网络错误，请重试', 'error');"
"}"
"btn.disabled = false;"
"btn.textContent = '保存配置';"
"});"
"function resetConfig() {"
"document.getElementById('wifi_ssid').innerHTML = '<option value=\"\">-- 请先扫描 --</option>';"
"document.getElementById('wifi_password').value = '';"
"document.getElementById('mqtt_uri').value = '';"
"document.getElementById('mqtt_port').value = '1883';"
"document.getElementById('mqtt_username').value = '';"
"document.getElementById('mqtt_password').value = '';"
"hideStatus();"
"}"
"function showStatus(msg, type) {"
"const el = document.getElementById('status');"
"el.textContent = msg;"
"el.className = 'status ' + type;"
"el.style.display = 'block';"
"}"
"function hideStatus() {"
"document.getElementById('status').style.display = 'none';"
"}"
"loadConfig();"
"// OTA functions"
"function otaFileSelected(input) {"
"    console.log('otaFileSelected called');"
"    const file = input.files[0];"
"    console.log('file:', file ? file.name : 'null');"
"    if (file) {"
"        document.getElementById('otaFileName').textContent = '已选择: ' + file.name + ' (' + (file.size / 1024).toFixed(1) + ' KB)';"
"        const btn = document.getElementById('otaUploadBtn');"
"        btn.disabled = false;"
"        btn.style.background = '#dc3545';"
"        btn.style.cursor = 'pointer';"
"        console.log('Button enabled');"
"        // Calculate CRC32"
"        const reader = new FileReader();"
"        reader.onload = function(e) {"
"            const data = new Uint8Array(e.target.result);"
"            const crc = calcCrc32(data);"
"            const crcEl = document.getElementById('otaCrc');"
"            crcEl.textContent = 'CRC32: 0x' + crc.toString(16).toUpperCase().padStart(8, '0');"
"            crcEl.style.display = 'block';"
"            console.log('CRC32 calculated:', crc.toString(16));"
"        };"
"        reader.readAsArrayBuffer(file);"
"    } else {"
"        console.log('No file selected');"
"    }"
"}"
"// CRC32 calculation (same algorithm as device)"
"function calcCrc32(data) {"
"    let crc = 0xFFFFFFFF;"
"    const table = new Uint32Array(256);"
"    for (let i = 0; i < 256; i++) {"
"        let c = i;"
"        for (let j = 0; j < 8; j++) {"
"            c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);"
"        }"
"        table[i] = c;"
"    }"
"    for (let i = 0; i < data.length; i++) {"
"        crc = table[(crc ^ data[i]) & 0xFF] ^ (crc >>> 8);"
"    }"
"    return (crc ^ 0xFFFFFFFF) >>> 0;"
"}"
"async function otaUpload() {"
"    const fileInput = document.getElementById('otaFile');"
"    const file = fileInput.files[0];"
"    const user = document.getElementById('otaUser').value;"
"    const pass = document.getElementById('otaPass').value;"
"    if (!file) { alert('请先选择固件文件'); return; }"
"    if (!user || !pass) { alert('请输入用户名和密码'); return; }"
"    if (!confirm('确定要升级固件吗？升级过程中请勿断电！\\n固件: ' + file.name + ' (' + (file.size / 1024).toFixed(1) + ' KB)')) return;"
"    const progress = document.getElementById('otaProgress');"
"    const bar = document.getElementById('otaProgressBar');"
"    const status = document.getElementById('otaStatus');"
"    progress.style.display = 'block';"
"    bar.style.width = '0%';"
"    status.textContent = '上传中...';"
"    status.style.color = '#666';"
"    try {"
"        const xhr = new XMLHttpRequest();"
"        xhr.open('POST', '/api/ota', true);"
"        // Add Basic Auth header"
"        const auth = btoa(user + ':' + pass);"
"        xhr.setRequestHeader('Authorization', 'Basic ' + auth);"
"        xhr.upload.onprogress = function(e) {"
"            if (e.lengthComputable) {"
"                const pct = Math.round((e.loaded / e.total) * 100);"
"                bar.style.width = pct + '%';"
"                status.textContent = '上传中... ' + pct + '%';"
"            }"
"        };"
"        xhr.onload = function() {"
"            if (xhr.status === 200) {"
"                bar.style.width = '100%';"
"                status.textContent = '升级成功！设备即将重启...';"
"                status.style.color = '#28a745';"
"            } else if (xhr.status === 401) {"
"                status.textContent = '认证失败：用户名或密码错误';"
"                status.style.color = '#dc3545';"
"            } else {"
"                status.textContent = '升级失败: ' + xhr.status + ' ' + xhr.statusText;"
"                status.style.color = '#dc3545';"
"            }"
"        };"
"        xhr.onerror = function() {"
"            status.textContent = '上传失败，请重试';"
"            status.style.color = '#dc3545';"
"        };"
"        xhr.send(file);"
"    } catch(e) {"
"        status.textContent = '上传异常: ' + e.message;"
"        status.style.color = '#dc3545';"
"    }"
"}"
"// Auto scan WiFi when page loads"
"window.addEventListener('load', () => {"
"    setTimeout(scanWiFi, 500);"
"});"
"</script>"
"</body>"
"</html>";

#endif
